---
title: "Python for Non-Programmers"
author: "Ahmad Nadeem"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    fig_width: 8
    fig_height: 5
    fig_caption: TRUE
    highlight: "kate"
    lightbox: TRUE
    thumbnails: TRUE
    gallery: TRUE
    toc_depth: 3
    embed_fonts: TRUE
    use_bookdown: TRUE
    pandoc_args: NULL
    md_extensions: NULL
    mathjax: "rmdformats"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    comment = NA
  , echo = TRUE
  )
library(reticulate)
```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(
    lang     = c('r', 'python')
  , position = c('top', 'right')
  )
```

```{r, child='01.Introduction.Rmd', eval = FALSE}

```


```{r, child='02.Module_PIP_Comments.Rmd'}

```


```{r, child='03.Variables.Rmd'}

```


```{r, child='04.Strings.Rmd'}

```


```{r, child='05.Lists_Tuples.Rmd'}

```


```{r, child='06.Dict_Sets.Rmd'}

```


```{r, child='07.Cond_Expressions.Rmd'}

```


```{r, child='08.Loops.Rmd'}

```


```{r, child='09.List_Comprehension.Rmd'}

```


```{r, child='10.Functions_Recursion.Rmd'}

```